version: '3.8'
services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    ports:
      - "3000:3000"
    container_name: server
    volumes:
      - ./server:/app